### ISSUE TITLE
[infra] checks and balances

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/mais#376]
# Metadata Checks
 - action independente
 - usa pytest  (confirmar)
 - roda em todo commit do PR

## List of checks
- descrições não vazias
- yaml com lint válido
- topo do yaml estar batendo com o que está no BQ
- verificar se campos estão seguindo padrões (ex: frequencia de atualização, abrangência, etc...)
- colunas padrão (id_municipio, uf, ...) tem que ter a mesma descrição/tipo
- checar se prefixos não são [tp, cd, qt]

# Data Checks
- action
- Query no BQ dev --> procura 
- roda somente qdo adicionar label (ou algo assim)
- roda condicionamente a existencia da coluna

checks.yaml
```
checks:
    - name: select all
       description: 
       query: |
        SELECT * FROM {{ project_id }}.{{ dataset_id }}.{{ table_id}}

     - name: check id_municipio
        description: 
        depends_on_columns: [id_municipio*]
        query: |
        select {% for %}  estão contidos na tabela de ids municipio
```

## List of checks
- select all
- not colunas totalmente nulas
- primary keys tem que ser únicas e não nulas
- checar se colunas padrão existem em index. Ex: id_municipio* está contido em diretorio_municipio
- formato de data/hora: YYYY-MM-DD HH:MM:SS
